Global displacement
CSIS-iLab/ppd-viz pull request #2
Opened 2018-09-06 12:54 UTC by aleesteele

Basic global displacement chart, no styling

2018-09-07 14:12 UTC, jnschrag requested changes
- Since we're starting from scratch with these, can you go ahead and remove the jQuery dependency?
- Please update the `<title>` tag with the title of the chart
- The zoom in feature is nice to have, however, the X axis can start having decimals on them. Can you look at making sure the year numbers stay whole numbers?

2018-09-07 16:35 UTC, aleesteele commented
- refactored for vanilla javascript 
- deleted jquery label & removed library
- kept x-axis whole numbers (years)
- rounded point values & removed extra x-axis label

Q's: should I add 'millions' to the point labels themselves?

2018-09-11 13:54 UTC, aleesteele commented
- Horizontal wide gridlines
- Capitalized y-axis labels / custom labels w/ mil
- Normal weight legend

Q's:
- Didn't change # of x-axis ticks, there might be too much

2018-09-17 15:01 UTC, jnschrag requested changes
This is really good, nicely done! Just a few small tweaks and then I'll accept it.

- Can you make sure that in `index.html` all of the external sources have `https:` at the beginning of their URLs?
- Make a copy of the iframeSizer and put it in PPD's global folder, then include it in the chart's `index.html`
- Add "People" as a value suffix in the tooltip

2018-09-17 15:01 UTC, jnschrag commented on globals/ppd-highcharts-theme.js
> +    headerFormat: "<span style=\"font-size: 13px;text-align:center;margin-bottom: 5px;font-weight: bold;font-family: 'Source Sans Pro', arial, sans-serif;\">{point.key}</span><br/>"
Let's remove the reference to "Source Sans Pro" here and make it Proxima Nova like the rest of the chart.

2019-01-28 20:23 UTC, aleesteele commented
Fixed this one up too!

2019-01-30 14:52 UTC, jnschrag approved these changes

2019-01-30 14:52 UTC, merged