Global oda - basic chart, no styling or 'source'
CSIS-iLab/ppd-viz pull request #4
Opened 2018-09-06 13:05 UTC by aleesteele

2018-09-07 14:14 UTC, jnschrag requested changes
- Let's remove the jQuery dependency and just run this on vanilla JS

2018-09-07 14:14 UTC, jnschrag commented on forced-migration/global-oda/js/area.js
> +    ['#4D6E79', '#303D43', '#907561', '#781F30', '#EC382A', '#61884D', '#C9AC4D', '#52496D', '#5AA992', '#887295', '#2576CE', '#aa266a'],
This is missing the `colors:` property so the chart doesn't work. Always be sure to check to make sure your chart works when submitting it for review.

2018-09-07 17:06 UTC, aleesteele commented on forced-migration/global-oda/js/area.js
> +    ['#4D6E79', '#303D43', '#907561', '#781F30', '#EC382A', '#61884D', '#C9AC4D', '#52496D', '#5AA992', '#887295', '#2576CE', '#aa266a'],
changed + pushed.

2018-09-07 17:08 UTC, aleesteele commented
- Rounded x-axis to whole numbers
- Corrected color
- Removed jquery
- Refactored for vanilla JS

2019-01-28 20:19 UTC, aleesteele commented
Saw these outstanding pull requests, and figured I'd fix 'em up!

2019-01-30 14:52 UTC, jnschrag approved these changes

2019-01-30 14:52 UTC, merged